const menuButton=document.querySelector(".menu-button");const nav=document.querySelector(".site-nav");const resourceMenu=document.querySelector(".resource-menu");const resourceTrigger=document.querySelector(".resource-trigger");
menuButton?.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});resourceTrigger?.addEventListener("click",event=>{event.stopPropagation();const open=resourceMenu.classList.toggle("open");resourceTrigger.setAttribute("aria-expanded",String(open))});document.addEventListener("click",event=>{if(!resourceMenu?.contains(event.target)){resourceMenu?.classList.remove("open");resourceTrigger?.setAttribute("aria-expanded","false")}});

const tasks=[
  {title:"做课件与教学展示",description:"从五款 AI PPT 工具中，找到更适合自己备课习惯的一款。",tools:[["希沃 Bloom","预制教师备课流程，课件可编辑并自带互动游戏","Joy 推荐","https://www.bilibili.com/video/BV1Py6dBwExW/","B站"],["豆包生成 PPT","看看豆包完成真实教学课件的表现","同题测评","https://www.bilibili.com/video/BV1VaZAB3EnA/","B站"],["Kimi 生成 PPT","测试内容组织与图片匹配能力","同题测评","https://www.bilibili.com/video/BV1QWzsBnEGz/","B站"],["Canva 可画生成 PPT","测试视觉设计与后续编辑体验","同题测评","https://www.bilibili.com/video/BV1ubkeBSEmF/","B站"],["扣子生成 PPT","基础生成与风格克隆两种方式","同题测评","https://www.bilibili.com/video/BV1Ag6qBkEkZ/","B站"]]},
  {title:"整理资料与听评课",description:"把课本、音视频和公开课资料，整理成真正可以继续使用的教学内容。",tools:[["NotebookLM 遇上生物课本","从音频、视频到 PPT，手把手完成定制备课","长视频教程","https://www.bilibili.com/video/BV1mr2kB7Eei/","B站"],["千问智能体：音视频提取","完成听评课笔记、PPT 逐字稿与教研整理","快速上手","https://www.bilibili.com/video/BV1KA2kB5E9X/","B站"]]},
  {title:"制作微课与教学视频",description:"按不同视频类型选择工具，从快速活动视频到讲题和白板动画。",tools:[["小云雀 AI 视频","脚本和分镜可编辑，适合备课视频","近期测评","https://www.bilibili.com/video/BV1XwDEBhEFK/","B站"],["剪映一键生成视频","活动视频五分钟快速成片","快速上手","https://www.xiaohongshu.com/explore/6913cc5d000000000703b3d1","小红书"],["秘塔生成讲题视频","一键生成试题讲解视频","讲题工具","https://www.bilibili.com/video/BV18bwczgEsX/","B站"],["VideoScribe 手绘视频","制作微课、公开课和赛课白板动画","创意工具","https://www.bilibili.com/video/BV1BbiqBREH4/","B站"]]}
];
const buttons=[...document.querySelectorAll(".task-button")],label=document.querySelector(".bench-label"),title=document.querySelector(".bench-header h3"),description=document.querySelector(".bench-header p"),results=document.querySelector(".tool-results");
const renderTask=index=>{const task=tasks[index];buttons.forEach((button,i)=>{const active=i===index;button.classList.toggle("active",active);button.setAttribute("aria-selected",String(active))});label.textContent=`TASK ${String(index+1).padStart(2,"0")}`;title.textContent=task.title;description.textContent=task.description;results.innerHTML=task.tools.map(([name,summary,best,link,platform],i)=>`<article class="tool-result"><span class="result-rank">${String(i+1).padStart(2,"0")}</span><div class="result-copy"><h4>${name}</h4><p>${summary}</p></div><span class="result-best">${best} · ${platform}</span><a class="result-link" href="${link}" target="_blank" rel="noreferrer" aria-label="观看视频：${name}"><i data-lucide="arrow-up-right"></i></a></article>`).join("");lucide.createIcons()};
buttons.forEach((button,index)=>button.addEventListener("click",()=>renderTask(index)));renderTask(0);
