const menuButton=document.querySelector(".menu-button");const nav=document.querySelector(".site-nav");const resourceMenu=document.querySelector(".resource-menu");const resourceTrigger=document.querySelector(".resource-trigger");
menuButton?.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});resourceTrigger?.addEventListener("click",event=>{event.stopPropagation();const open=resourceMenu.classList.toggle("open");resourceTrigger.setAttribute("aria-expanded",String(open))});document.addEventListener("click",event=>{if(!resourceMenu?.contains(event.target)){resourceMenu?.classList.remove("open");resourceTrigger?.setAttribute("aria-expanded","false")}});

const topics=[
  {number:"01",audience:"面向一线教师",title:"AI 赋能学科教学与教师减负",description:"帮助老师建立 AI 认知框架，掌握提示词、备课四件套与学科教学应用，让 AI 从新鲜工具变成日常工作流。",courses:["AI 赋能学科教学课程","高效工具助力教师减负增效","从知道 AI 到用好 AI：构建教师 AI 工作流","未来教师，AI 助您站稳讲台"],takeaways:["完成一套 AI 备课实践","掌握高质量提示词方法","获得可继续使用的学习资源"]},
  {number:"02",audience:"面向校长与管理者",title:"AI 赋能学校管理与未来教育",description:"围绕学校治理、行政事务、数据分析、教师发展与品牌传播，帮助管理者看见 AI 在学校中的落地路径。",courses:["AI 赋能学校管理课程","AI 时代：未来教育新样态","智慧校园与教师发展专题"],takeaways:["梳理学校 AI 行动方向","发现管理减负场景","形成可落地的应用清单"]},
  {number:"03",audience:"面向骨干教师与教研团队",title:"AI 驱动教科研与实践工作坊",description:"从课题选题、文献综述、研究方法到写作修改，同时结合教学工具工作坊，让教师完成真实任务。",courses:["研究引擎：AI 驱动教师课题与论文突破","AI 工具教学实践工作坊","DeepSeek × Canva 教学实践","教师原创资源数字化生产工作坊"],takeaways:["走通教科研全流程","完成现场实操作品","建立团队后续实践方向"]}
];let active=0;const tabs=document.querySelector(".topic-tabs"),panel=document.querySelector(".topic-panel");
const render=()=>{tabs.innerHTML=topics.map((topic,index)=>`<button class="topic-tab ${index===active?"active":""}" type="button" role="tab" aria-selected="${index===active}"><b>${topic.number}</b><span>${topic.audience}</span></button>`).join("");const topic=topics[active];panel.innerHTML=`<div class="topic-intro"><span>${topic.audience}</span><h3>${topic.title}</h3><p>${topic.description}</p></div><div class="topic-courses"><strong>可定制培训专题</strong>${topic.courses.map(item=>`<span><i data-lucide="sparkles"></i><b>${item}</b></span>`).join("")}</div><div class="topic-results"><strong>预期培训成果</strong>${topic.takeaways.map(item=>`<span><i data-lucide="check"></i>${item}</span>`).join("")}</div>`;[...tabs.children].forEach((button,index)=>button.addEventListener("click",()=>{active=index;render()}));lucide.createIcons()};render();lucide.createIcons();
